spring.application.name=pharmacy
spring.datasource.url=jdbc:postgresql://database-1.cpywk0uq2d08.us-east-2.rds.amazonaws.com:5432/pharmacydb
spring.datasource.username=postgres
spring.datasource.password=GauravPitts9!
# Tells Hibernate to update the schema or create tables if they do not exist
spring.jpa.hibernate.ddl-auto=update

# Ensures Spring Boot triggers the DDL generation process
spring.jpa.generate-ddl=true

# Useful for debugging: prints the generated SQL to your console
spring.jpa.show-sql=true